spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=canopener
    username: "sa"
    password: "Sup3r-S3cr3t"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    database: sql_server

    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:db/liquibase-changelog.xml
    user: "sa"
    password: "Sup3r-S3cr3t"
